---
to: components/Modal/registerModalDialog.ts
unless_exists: true
---
// DO NOT EDIT IN ANY WAY AFTER INITIAL SETUP STEPS!!
// Autogenerated file.
import { NiceModalHocProps, create as createModal } from "@ebay/nice-modal-react";
import { ComponentType, FC } from "react";

/**
 * Function used to register modal dialogs for usage inside the app. This function allows modal dialogs to be used with `useModalDialog` hook after they have been registered.
 *
 * `useModalDialog` should only be used inside modal components directly and in custom hook that is created for each modal.
 */
export const registerModalDialog = createModal as <P extends BASE_MODAL_PROPS_TYPE>(Comp: ComponentType<P>) => FC<P & NiceModalHocProps>;
