# Simple workflow that does these steps on pull request to certain branches:
# 1. Install npm dependencies (with caching enabled)
# 2. Run JS/TS linting

name: Lint and typecheck

on:
  pull_request:
    branches:
      - main
      - develop
      - "sprint/**"

jobs:
  check:
    name: Lint on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
        # Checkout code from repo
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          # Fetch all history for all branches and tags (https://github.com/actions/checkout?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches)
          fetch-depth: 0

        # Setup Node.js to be used inside this runner
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install npm packages
        # We don't need audit during CI. Also, prefer locally cached dependencies if that's possible
        run: npm ci --prefer-offline --no-audit

        # Lint code using Biome (https://biomejs.dev/)
      - name: Lint code
        run: npx biome lint --error-on-warnings --files-ignore-unknown=true src/
        if: ${{ success() || failure() }}

        # Run TypeScript to check if types are valid inside the project
      - name: Run TypeScript type check
        run: npx tsc --noEmit --pretty
        if: ${{ success() || failure() }}
